# Generated by Django 5.1.4 on 2025-02-06 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board",
            old_name="board_id",
            new_name="id",
        ),
    ]
