# Generated by Django 5.1.4 on 2025-02-18 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
